# Ultralytics YOLO 🚀, AGPL-3.0 license
# Builds ultralytics/ultralytics:latest-arm64 image on DockerHub https://hub.docker.com/r/ultralytics/ultralytics
# Image is aarch64-compatible for Apple M1, M2, M3, Raspberry Pi and other ARM architectures

# Start FROM Ubuntu image https://hub.docker.com/_/ubuntu with "FROM arm64v8/ubuntu:22.04" (deprecated)
# Start FROM Debian image for arm64v8 https://hub.docker.com/r/arm64v8/debian (new)
FROM arm64v8/debian:bullseye-slim
ENV DEBIAN_FRONTEND=noninteractive

RUN echo "deb https://packages.cloud.google.com/apt coral-edgetpu-stable main" | tee /etc/apt/sources.list.d/coral-edgetpu.list
RUN apt-get update && apt-get install -y curl python3 python3-pip git
RUN curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
RUN echo "libedgetpu libedgetpu/accepted-eula boolean true" | debconf-set-selections && apt-get update && apt-get install -y libedgetpu1-max python3-pycoral ffmpeg libsm6 libxext6 build-essential

RUN git clone https://github.com/ultralytics/ultralytics /usr/src/yolov8
WORKDIR /usr/src/yolov8
RUN python3 -m pip install ultralytics websockets lapx
