FROM arm64v8/debian:bullseye-slim
ENV DEBIAN_FRONTEND=noninteractive

RUN echo "deb https://packages.cloud.google.com/apt coral-edgetpu-stable main" | tee /etc/apt/sources.list.d/coral-edgetpu.list
RUN apt-get update && apt-get install -y curl python3 python3-pip git
RUN curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
# RUN echo "libedgetpu libedgetpu/accepted-eula boolean true" | debconf-set-selections && apt-get update && apt-get install -y libedgetpu1-max python3-pycoral ffmpeg libsm6 libxext6 build-essential
RUN apt-get update && apt-get install -y libedgetpu1-std python3-pycoral ffmpeg libsm6 libxext6 build-essential
# RUN apt-get update && apt-get install -y python3-pycoral ffmpeg libsm6 libxext6

RUN git clone https://github.com/ultralytics/ultralytics /usr/src/yolov8
WORKDIR /usr/src/yolov8
RUN python3 -m pip install ultralytics