# Ultralytics YOLO 🚀, AGPL-3.0 license
# Builds ultralytics/ultralytics:latest-arm64 image on DockerHub https://hub.docker.com/r/ultralytics/ultralytics
# Image is aarch64-compatible for Apple M1, M2, M3, Raspberry Pi and other ARM architectures

# Start FROM Ubuntu image https://hub.docker.com/_/ubuntu with "FROM arm64v8/ubuntu:22.04" (deprecated)
# Start FROM Debian image for arm64v8 https://hub.docker.com/r/arm64v8/debian (new)
FROM arm64v8/debian:bullseye-slim
ENV DEBIAN_FRONTEND=noninteractive
# Downloads to user config dir
# ADD https://github.com/ultralytics/assets/releases/download/v0.0.0/Arial.ttf \
#     https://github.com/ultralytics/assets/releases/download/v0.0.0/Arial.Unicode.ttf \
#     /root/.config/Ultralytics/

# # Install linux packages
# # g++ required to build 'tflite_support' and 'lap' packages, libusb-1.0-0 required for 'tflite_support' package
# # cmake and build-essential is needed to build onnxsim when exporting to tflite
# RUN apt-get update \
#     && apt-get install --no-install-recommends -y python3-pip git zip curl gcc libgl1 libglib2.0-0 libpython3-dev gnupg g++ libusb-1.0-0 build-essential

# # Create working directory
# WORKDIR /usr/src/ultralytics

# # Copy contents
# # COPY . /usr/src/ultralytics  # git permission issues inside container
# RUN git clone https://github.com/ultralytics/ultralytics -b main /usr/src/ultralytics
# ADD https://github.com/ultralytics/assets/releases/download/v8.1.0/yolov8n.pt /usr/src/ultralytics/

# # Remove python3.11/EXTERNALLY-MANAGED to avoid 'externally-managed-environment' issue, Debian 12 Bookworm error
# RUN rm -rf /usr/lib/python3.11/EXTERNALLY-MANAGED

# # Install pip packages
# RUN python3 -m pip install --upgrade pip wheel
# RUN python3 -m pip install --no-cache -e ".[export]"
# RUN python3 -m pip install tflite-runtime
# # Creates a symbolic link to make 'python' point to 'python3'
# RUN ln -sf /usr/bin/python3 /usr/bin/python

RUN echo "deb https://packages.cloud.google.com/apt coral-edgetpu-stable main" | tee /etc/apt/sources.list.d/coral-edgetpu.list
RUN apt-get update && apt-get install -y curl python3 python3-pip git
RUN curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
# RUN echo "libedgetpu libedgetpu/accepted-eula boolean true" | debconf-set-selections && apt-get update && apt-get install -y libedgetpu1-max python3-pycoral ffmpeg libsm6 libxext6 build-essential
RUN apt-get update && apt-get install -y libedgetpu1-std python3-pycoral ffmpeg libsm6 libxext6 build-essential
# RUN apt-get update && apt-get install -y python3-pycoral ffmpeg libsm6 libxext6 

RUN git clone https://github.com/ultralytics/ultralytics /usr/src/yolov8
WORKDIR /usr/src/yolov8
RUN python3 -m pip install ultralytics
