<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="fobo2">

    <!-- Define parameters of chassis -->
    <xacro:property name="chassis_length" value="0.55"/>
    <xacro:property name="chassis_width" value="0.35"/>
    <xacro:property name="chassis_depth" value="0.01"/>
    <xacro:property name="chassis_mass" value="0.654"/>
    <!-- Motor cylinder parameters -->
    <xacro:property name="motor_radius" value="0.032"/>
    <xacro:property name="motor_length" value="0.105"/>
    <xacro:property name="motor_mass" value="0.438"/>
    <xacro:property name="motor_offset" value="0.01"/>
    <!-- wheel parameters -->
    <xacro:property name="wheel_radius" value="0.12"/>
    <xacro:property name="wheel_length" value="0.088"/>
    <xacro:property name="wheel_mass" value="0.237"/>
    <!-- Ball parameters -->
    <xacro:property name="ball_radius" value="0.030"/>
    <xacro:property name="ball_mass" value="1"/>
    <xacro:property name="stick_offset" value="0.05"/>
    <xacro:property name="stick_radius" value="0.015"/>
    <xacro:property name="stick_mass" value="0.015"/>
    <!-- Stick length can't be automatically calculated -->
    <xacro:property name="stick_length" value="0.102" />


    <!-- define colors -->
    <material name="white">
        <color rgba="1 1 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>


    <xacro:macro name="cylinder_inertia" params="m r h">
        <inertia  ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0"
                    iyy="${m*(3*r*r+h*h)/12}" iyz = "0"
                    izz="${m*r*r/2}" /> 
    </xacro:macro>


    <xacro:macro name="box_inertia" params="m x y z">
        <inertia  ixx="${m*(y*y+z*z)/12}" ixy = "0" ixz = "0"
                    iyy="${m*(x*x+z*z)/12}" iyz = "0"
                    izz="${m*(x*x+z*z)/12}" /> 
    </xacro:macro>

    <xacro:macro name="sphere_inertia" params="m r">
        <inertia  ixx="${2*m*r*r/5}" ixy = "0" ixz = "0"
                    iyy="${2*m*r*r/5}" iyz = "0"
                    izz="${2*m*r*r/5}" /> 
    </xacro:macro>


    <!-- link macros -->
    <xacro:macro name="box_link" params="link_name length width depth mass color">
        <link name="${link_name}">
            <visual>
            <geometry>
                <box size="${length} ${width} ${depth}"/>
            </geometry>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <material name="${color}">
                    <!-- <color rgba="1 1 1 1"/> -->
                </material>
            </visual>
            <collision>
            <geometry>
                <box size="${length} ${width} ${depth}"/>
            </geometry>
                <origin rpy="0 0 0" xyz="0 0 0"/>
            </collision>
            <inertial>
                <mass value="${mass}"/>
                <xacro:box_inertia m="${mass}" x="${length}" y="${width}" z="${depth}" />
            </inertial>
        </link>
    </xacro:macro>


    <xacro:macro name="cylinder_link" params="link_name radius length mass color">
        <link name="${link_name}">
            <visual>
                <geometry>
                    <cylinder radius="${radius}" length="${length}"/>
                </geometry>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <material name="${color}">
                    <color rgba="1 1 1 1"/>
                </material>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${radius}" length="${length}"/>
                </geometry>
                <origin rpy="0 0 0" xyz="0 0 0"/>
            </collision>
            <inertial>
                <mass value="${mass}"/>
                <xacro:cylinder_inertia m="${mass}" r="${radius}" h="${length}" />
            </inertial>
        </link>
    </xacro:macro>

    <xacro:macro name="sphere_link" params="link_name radius mass color">
        <link name="${link_name}">
            <visual>
                <geometry>
                    <sphere radius="${radius}" />
                </geometry>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <material name="${color}">
                    <color rgba="1 1 1 1"/>
                </material>
            </visual>
            <collision>
                <geometry>
                    <sphere radius="${radius}" />
                </geometry>
                <origin rpy="0 0 0" xyz="0 0 0"/>
            </collision>
            <inertial>
                <mass value="${mass}"/>
                <xacro:sphere_inertia m="${mass}" r="${radius}" />
            </inertial>
        </link>
    </xacro:macro>



    <!-- Define links joints macros  -->
    <xacro:macro name="static_joint" params="name parent child xyz rpy">
        <joint name="${name}" type="fixed">
            <parent link="${parent}" />
            <child link="${child}" />
            <origin xyz="${xyz}" rpy="${rpy}"/>
        </joint>
    </xacro:macro>

    <xacro:macro name="wheel_joint" params="name parent child xyz">
        <joint name="${name}" type="continuous">
            <parent link="${parent}" />
            <child link="${child}" />
            <origin xyz="${xyz}" rpy="0 0 0"/>
            <axis xyz="0 0 1"/> 
        </joint>
    </xacro:macro>
    <xacro:macro name="sphere_joint" params="name parent child xyz">
        <joint name="${name}" type="spherical">
            <parent link="${parent}" />
            <child link="${child}" />
            <origin xyz="${xyz}" rpy="0 0 0"/>
            <axis xyz="0 0 1"/> 
        </joint>
    </xacro:macro>


    <!-- Base link -->
    <xacro:box_link link_name="base_link" length="${chassis_length}" width="${chassis_width}" depth="${chassis_depth}" mass="${chassis_mass}" color="white" />
    <!-- Motor links -->
    <xacro:cylinder_link link_name="motor-right" radius="${motor_radius}" length="${motor_length}" mass="${motor_mass}" color="white" />
    <xacro:cylinder_link link_name="motor-left" radius="${motor_radius}" length="${motor_length}" mass="${motor_mass}" color="white" />
    <!-- Wheel links -->
    <xacro:cylinder_link link_name="wheel-right" radius="${wheel_radius}" length="${wheel_length}" mass="${wheel_mass}" color="black" />
    <xacro:cylinder_link link_name="wheel-left" radius="${wheel_radius}" length="${wheel_length}" mass="${wheel_mass}" color="black" />
    <!-- Ball links -->
    <xacro:cylinder_link link_name="stick-front" radius="${stick_radius}" length="${stick_length}" mass="${stick_mass}" color="black" />
    <xacro:cylinder_link link_name="stick-back" radius="${stick_radius}" length="${stick_length}" mass="${stick_mass}" color="black" />
    <xacro:sphere_link link_name="ball-front" radius="${ball_radius}" mass="${ball_mass}" color="red" />
    <xacro:sphere_link link_name="ball-back" radius="${ball_radius}" mass="${ball_mass}" color="red" />

    <!-- Motor joints -->
    <xacro:static_joint name="motor-right-base" parent="base_link" child="motor-right" xyz="0 ${chassis_width/2 - motor_length/2  + motor_offset} ${-(chassis_depth + motor_radius/2)}" rpy="0 1.5707 1.5707"/>
    <xacro:static_joint name="motor-left-base" parent="base_link" child="motor-left" xyz="0 ${-(chassis_width/2 - motor_length/2 + motor_offset)} ${-(chassis_depth + motor_radius/2)}" rpy="0 1.5707 1.5707"/>
    <!-- Wheel joints -->
    <xacro:wheel_joint name="wheel-motor-right" parent="motor-right" child="wheel-right" xyz="0 0 ${motor_length/2 + wheel_length/2}"/>
    <xacro:wheel_joint name="wheel-motor-left" parent="motor-left" child="wheel-left" xyz="0 0 ${-(motor_length/2 + wheel_length/2)}"/>
    <!-- Ball joints -->
    <xacro:static_joint name="stick-front-base" parent="base_link" child="stick-front" xyz="${chassis_length/2 - stick_offset} 0 ${-stick_length/2}" rpy="0 0 0" />
    <xacro:static_joint name="stick-back-base" parent="base_link" child="stick-back" xyz="${-(chassis_length/2 - stick_offset)} 0 ${-stick_length/2s}" rpy="0 0 0" />
    <xacro:sphere_joint name="ball-front-joint" parent="base_link" child="ball-front" xyz="${chassis_length/2 - stick_offset} 0 ${-chassis_depth - wheel_radius + ball_radius/2}" />
    <xacro:sphere_joint name="ball-back-joint" parent="base_link" child="ball-back" xyz="${-(chassis_length/2 - stick_offset)} 0 ${-chassis_depth - wheel_radius + ball_radius/2}" />
    

</robot>