version: "3.0"
services:
  train-fobo-sac:
    restart: on-failure
    container_name: train-fobo-sac
    image: inigo183/train-fobo:latest
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /home/izarate/datos:/usr/src/data
      - /home/izarate/train_utils/train_fobo.py:/usr/src/train_fobo.py
      - /home/izarate/train_utils/hyperparameters:/usr/src/hyperparameters
      - /home/izarate/fobo2_env:/usr/src/fobo2_env
    environment:
      - TRAIN_MODE=DIRECT
      - SAVE_MODEL_PATH=/usr/src/data
      - MODEL_TYPE=sac
      - USED_GPU=0
      - ENV_VERSION=0.4.3
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0', '1', '2']
            capabilities: [gpu]
  train-fobo-ppo:
    restart: on-failure
    container_name: train-fobo-ppo
    image: inigo183/train-fobo:latest
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /home/izarate/datos:/usr/src/data
      - /home/izarate/train_utils/train_fobo.py:/usr/src/train_fobo.py
      - /home/izarate/train_utils/hyperparameters:/usr/src/hyperparameters
      - /home/izarate/fobo2_env:/usr/src/fobo2_env
    environment:
      - TRAIN_MODE=DIRECT
      - SAVE_MODEL_PATH=/usr/src/data
      - MODEL_TYPE=ppo
      - USED_GPU=1
      - ENV_VERSION=0.4.3
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0', '1', '2']
            capabilities: [gpu]